import mysql from 'mysql2';
import dotenv from 'dotenv';

dotenv.config();

const pool = mysql.createPool({
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    password: process.env.DB_PASS,
    database: process.env.DB_NAME,
});
const db = pool.promise();

async function fixPassword() {
    try {
        const email = 'turawebdesigns@gmail.com';
        // This is the hash generated by bcryptjs for 'password123' in the previous step
        const validHash = '$2a$10$OIg5xur96Vpk2NBcn4hyP.7K188IlR2217wZBTJiyVPmG2.xC8JcW';

        console.log(`Updating password for ${email}...`);
        const [result] = await db.query('UPDATE users SET password_hash = ? WHERE email = ?', [validHash, email]);

        console.log(`Changed ${result.changedRows} rows.`);
        if (result.changedRows > 0) {
            console.log("✅ Password has been updated to 'password123' (verified hash).");
        } else {
            console.log("⚠️ No rows changed. Either user not found or hash was already same.");
        }
        process.exit(0);
    } catch (err) {
        console.error("Error:", err);
        process.exit(1);
    }
}

fixPassword();
